#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Constantes
"""
# Seuils GEREP :
# https://www.legifrance.gouv.fr/loda/article_lc/LEGIARTI000041615540
# nota : certaines substances n'ont pas été retrouvées pour l'eau dans IREP,
# sans doute à cause des différentes appelations possible pour une même molécule
GEREP_THRESHOLDS = {
    "air": {
        "1,1,1-trichloroéthane (TCE)": 100,
        "1,1,2,2-tetrachloroéthane": 50,
        "1,2-dichloroéthane (DCE - chlorure d'éthylène)": 1000,
        "1,2,3,4,5,6-hexachlorocyclohexane (HCH)": 10,
        "1,3-butadiène": 15000,
        "1,4-dioxane": 1000,
        "Acétaldéhyde (aldéhyde acétique  éthanal)": 200,
        "Acide cyanhydrique (HCN)": 200,
        "Acrylonitrile": 1000,
        "Aldéhyde formique (formaldéhyde)": 1000,
        "Ammoniac (NH3)": 10000,
        "Antimoine et composés (exprimés en tant que Sb)": 10,
        "Arsenic et composés (exprimés en tant que As)": 20,
        "Benzène": 1000,
        "Cadmium et composés (exprimés en tant que Cd)": 10,
        "Chlore et composés inorganiques (en tant que HCl)": 10000,
        "Chlorofluorocarbures (CFC)": 1,
        "Chlorométhane (chlorure de méthyle)": 15000,
        "Chlorure de vinyle (chloroéthène)": 1000,
        "Chrome et composés (exprimés en tant que Cr)": 100,
        "Cobalt et composés (exprimés en tant que Co)": 5,
        "Composés organiques volatils non méthaniques (COVNM)": 30000,
        "Cuivre et composés (exprimés en tant que Cu)": 100,
        "Dichlorométhane (DCM, chlorure de méthylène)": 1000,
        "Dioxyde de carbone (CO2) total (d'origine biomasse et non biomasse)": 10000000,
        "Epichlorhydrine (1-chloro-2,3-époxypropane)": 100,
        "Fluor et composés inorganiques (en tant que HF)": 5000,
        "Halons": 1,
        "Hexafluorure de soufre (SF6)": 20,
        "Hydrazine": 100,
        "Hydrocarbures aromatiques polycycliques (HAP)": 50,
        "Hydrochlorofluorocarbures (HCFC)": 1,
        "Hydroflurocarbures (HFC)": 100,
        "Manganèse et composés (exprimés en tant que Mn)": 200,
        "Mercure et composés (exprimés en tant que Hg)": 10,
        "Méthane (CH4)": 100000,
        "Méthanol (alcool méthylique)": 20000,
        "Monoxyde de carbone (CO)": 500000,
        "Naphthalène": 50,
        "Nickel et composés (exprimés en tant que Ni)": 50,
        "Oxyde d'éthylène": 1000,
        "Oxyde de propylène (1,2-époxypropane)": 2000,
        "Oxydes d'azote (NOx/NO2)": 100000,
        "Oxydes de soufre (SOx/SO2)": 150000,
        "Particules (PM10)": 50000,
        "PCB-DL : somme des 12 PCB-DL (Somme de PCB77+PCB81+PCB105+PCB114+PCB118+PCB123+PCB126+PCB156+PCB157+PCB167+PCB169+PCB189)": 1,
        "PCBi : somme des 7 PCB indicateurs (PCB 28+PCB 52+PCB 101+PCB 118+PCB 138+PCB 153+PCB 180)": 1,
        "Dioxines et furanes (PCDD + PCDF) (exprimés en iTeq)": 0.0001,
        "Pentachlorobenzène": 0.0001,
        "Perfluorocarbures (PFC)": 100,
        "Phénols (en tant que C total)": 1000,
        "Plomb et composés (exprimés en tant que Pb)": 200,
        "Poussières totales": 100000,
        "Protoxyde d'azote (N2O)": 10000,
        "Sélénium": 20,
        "Sulfure d'hydrogène (H2S)": 3000,
        "Sulfure de carbone": 50000,
        "Tétrachlorométhane (TCM, tétrachlorure de carbone)": 2000,
        "Tétrachloroéthylène (PER, tétrachloroéthylène)": 100,
        "Thallium et ses composés (exprimés en tant que Tl)": 10,
        "Chloroforme (trichlorométhane)": 500,
        "Trifluorure d'azote (trifluoramine)": 500,
        "Vanadium et ses composés": 10,
        "Zinc et composés (exprimés en tant que Zn)": 200,
    },
    "eau": {
        "1,2-dichloroéthane (DCE - chlorure d'éthylène)": 10,
        "1,2,3,4,5,6-hexachlorocyclohexane (HCH)": 1,
        "Aldéhyde formique (formaldéhyde)": 300,
        "Aluminium et composés (exprimés en tant que Al)": 2000,
        "Anthracène": 1,
        "Arsenic et composés (exprimés en tant que As)": 5,
        "Azote total": 50000,
        "Benzène": 200,
        "Benzo (g, h, i) pérylène": 1,
        "Biphényles polychlorés (PCB)": 1,
        "Cadmium et composés (exprimés en tant que Cd)": 1,
        "Carbone organique total (en tant que C total ou DCO/3)": 50000,
        "Chloro-alkanes (C10-C13)": 1,
        "Chlorure de vinyle (chloroéthène)": 10,
        "Chlorures (en tant que Cl total)": 2000000,
        "Chrome et composés (exprimés en tant que Cr)": 50,
        "Chrome hexavalent et composés (exprimés en tant que Cr VI)": 30,
        "Cobalt et composés (exprimés en tant que Co)": 40,
        "Composés organohalogénés (exprimés en tant que AOX)": 1000,
        "Cuivre et composés (exprimés en tant que Cu)": 50,
        "Cyanures (sous forme de CN total)": 50,
        "Demande biologique en oxygène (DBO5)": 43000,
        "Demande chimique en oxygène (DCO)": 150000,
        "Dichlorométhane (DCM, chlorure de méthylène)": 10,
        "Diphényléthers bromés somme de : BDE 47, BDE 99, BDE 100, BDE 154, BDE 153, BDE 183 et BDE 209": 1,
        "Diuron": 1,
        "Etain et composés (exprimés en tant que Sn)": 200,
        "Ethylbenzène": 200,
        "Fer et composés (exprimés en tant que Fe)": 3000,
        "Fluoranthène": 1,
        "Fluorures (en tant que F total)": 2000,
        "Gamma isomère Lindane": 1,
        "Hexachlorobenzène (HCB)": 1,
        "Hexachlorobutadiène (HCBD)": 1,
        "Hydrocarbures": 10000,
        "Hydrocarbures aromatiques polycycliques (HAP)": 5,
        "Hydroxyde d'ammonium (NH4+)": 15000,
        "Manganèse et composés (exprimés en tant que Mn)": 500,
        "Matières en suspension (MES)": 300000,
        "Mercure et composés (exprimés en tant que Hg)": 1,
        "Méthanol (alcool méthylique)": 5000,
        "Naphthalène": 10,
        "Nickel et composés (exprimés en tant que Ni)": 20,
        "Nonylphénols et éthoxylates de nonylphénol (NP/NPE)": 1,
        "Octylphénols et éthoxylates d'octylphénol": 1,
        "PCBi : somme des 7 PCB indicateurs (PCB 28+PCB 52+PCB 101+PCB 118+PCB 138+PCB 153+PCB 180)": 1,
        "Dioxines et furanes (PCDD + PCDF) (exprimés en iTeq)": 0.0001,
        "Pentachlorobenzène": 1,
        "Pentachlorophénol (PCP)": 1,
        "Phénols (en tant que C total)": 20,
        "Phosphore total": 5000,
        "Di(2-éthylhexyle)phtalate (DEHP)": 1,
        "Plomb et composés (exprimés en tant que Pb)": 20,
        "Sulfates": 1500000,
        "Sulfonate de perfluorooctane (SPFO)": 0.0001,
        "Tétrachloroéthylène (PER, tétrachloroéthylène)": 10,
        "Tétrachlorométhane (TCM, tétrachlorure de carbone)": 1,
        "Titane et composés (exprimés en tant que Ti)": 100,
        "Toluène": 200,
        "Tributylphosphate": 1,
        "Trichloréthylène": 10,
        "Trichlorobenzènes (TCB) (tous les isomères)": 1,
        "Chloroforme (trichlorométhane)": 10,
        "Triphénylétain cation": 1,
        "Xylènes (somme ortho-xylène, méta-xylène, para-xylène)": 200,
        "Zinc et composés (exprimés en tant que Zn)": 100,
    },
    "sol": {
        "Aluminium et composés (exprimés en tant que Al)": 2000,
        "Arsenic et composés (exprimés en tant que As)": 5,
        "Azote total": 50000,
        "Biphényles polychlorés (PCB)": 1,
        "Cadmium et composés (exprimés en tant que Cd)": 5,
        "Chlorures (en tant que Cl total)": 2000000,
        "Chrome et composés (exprimés en tant que Cr)": 50,
        "Composés organohalogénés (exprimés en tant que AOX)": 30,
        "Cuivre et composés (exprimés en tant que Cu)": 50,
        "Fer et composés (exprimés en tant que Fe)": 3000,
        "Hydrocarbures aromatiques polycycliques (HAP)": 5,
        "Manganèse et composés (exprimés en tant que Mn)": 500,
        "Mercure et composés (exprimés en tant que Hg)": 1,
        "Nickel et composés (exprimés en tant que Ni)": 20,
        "PCBi : somme des 7 PCB indicateurs (PCB 28+PCB 52+PCB 101+PCB 118+PCB 138+PCB 153+PCB 180)": 1,
        "Phénols (en tant que C total)": 20,
        "Phosphore total": 5000,
        "Di(2-éthylhexyle)phtalate (DEHP)": 1,
        "Plomb et composés (exprimés en tant que Pb)": 20,
        "Sulfonate de perfluorooctane (SPFO)": 0,
        "Titane et composés (exprimés en tant que Ti)": 100,
        "Zinc et composés (exprimés en tant que Zn)": 100,
    },
}
